-- ============================================================================
-- API Keys table for REST API authentication
-- ============================================================================

CREATE TABLE public.api_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    key_prefix text NOT NULL,          -- First 8 chars for display (e.g. "ak_7f3b...")
    key_hash text NOT NULL,            -- SHA-256 hash of the full key
    created_by bigint NOT NULL REFERENCES sales(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz,
    revoked_at timestamptz,
    permissions jsonb NOT NULL DEFAULT '{"read": true, "write": true}'::jsonb
);

CREATE UNIQUE INDEX api_keys_hash_idx ON public.api_keys (key_hash);

ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

-- Admins can do everything
CREATE POLICY "api_keys_admin_all" ON public.api_keys
    FOR ALL TO authenticated
    USING (public.is_admin());

-- Non-admins can read their own keys
CREATE POLICY "api_keys_select_own" ON public.api_keys
    FOR SELECT TO authenticated
    USING (created_by IN (SELECT id FROM sales WHERE user_id = auth.uid()));

-- Grants
GRANT SELECT, INSERT, UPDATE, DELETE ON public.api_keys TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.api_keys TO service_role;
